/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-07-22 03:35:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;

public final class test_005fadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<title>検定管理システム</title>\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/view/css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/view/js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("    $('a,a img,button').css({\r\n");
      out.write("        opacity: 1.0,\r\n");
      out.write("        filter: \"alpha(opacity=100)\"\r\n");
      out.write("        }).hover(function(){\r\n");
      out.write("            $(this).fadeTo(200,0.6);\r\n");
      out.write("        },function(){\r\n");
      out.write("            $(this).fadeTo(200,1.0);\r\n");
      out.write("    })\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 List<String> arr; 
      out.write('\r');
      out.write('\n');
  arr = (List)request.getAttribute("list");
      out.write("\r\n");
      out.write("<header><h1><a href=\"main_admin.html\">検定管理システム</a></h1></header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"info\">\r\n");
      out.write("\t<h2>検定情報追加</h2>\r\n");
      out.write("\t");
 if (arr != null){ 
      out.write("\r\n");
      out.write("\t\t");
 for(int i = 0; i < arr.size(); i++) {
      out.write("\r\n");
      out.write("\t\t\t");
      out.print( arr.get(i) );
      out.write("\r\n");
      out.write("\t\t");
} 
      out.write('\r');
      out.write('\n');
      out.write('	');
} 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"cmfirmtestadd\" method=\"POST\">\r\n");
      out.write("\t<table class=\"list\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"testadd\">実施日</td>\r\n");
      out.write("\t\t\t<td class=\"testadd_main\">\r\n");
      out.write("\t\t\t\t<select name=\"jisshi_year\" class=\"drop\">\r\n");
      out.write("\t\t\t\t<optgroup label=\"年\">\r\n");
      out.write("\t\t\t\t<option value=\"2016\">2016年</option>\r\n");
      out.write("\t\t\t\t<option value=\"2015\">2015年</option>\r\n");
      out.write("\t\t\t\t<option value=\"2014\">2014年</option>\r\n");
      out.write("\t\t\t\t<option value=\"2013\">2013年</option>\r\n");
      out.write("\t\t\t\t<option value=\"2012\">2012年</option>\r\n");
      out.write("\t\t\t\t<option value=\"2011\">2011年</option>\r\n");
      out.write("\t\t\t\t<option value=\"2010\">2010年</option>\r\n");
      out.write("\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t</select><br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<select name=\"jisshi_month\" class=\"drop\">\r\n");
      out.write("\t\t\t\t<optgroup label=\"月\">\r\n");
      out.write("\t\t\t\t<option value=\"1\">1月</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">2月</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">3月</option>\r\n");
      out.write("\t\t\t\t<option value=\"4\">4月</option>\r\n");
      out.write("\t\t\t\t<option value=\"5\">5月</option>\r\n");
      out.write("\t\t\t\t<option value=\"6\">6月</option>\r\n");
      out.write("\t\t\t\t<option value=\"7\">7月</option>\r\n");
      out.write("\t\t\t\t<option value=\"8\">8月</option>\r\n");
      out.write("\t\t\t\t<option value=\"9\">9月</option>\r\n");
      out.write("\t\t\t\t<option value=\"10\">10月</option>\r\n");
      out.write("\t\t\t\t<option value=\"11\">11月</option>\r\n");
      out.write("\t\t\t\t<option value=\"12\">12月</option>\r\n");
      out.write("\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t</select><br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<select name=\"jisshi_day\" class=\"drop\">\r\n");
      out.write("\t\t\t\t<optgroup label=\"日\">\r\n");
      out.write("\t\t\t\t<option value=\"1\">1日</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">2日</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">3日</option>\r\n");
      out.write("\t\t\t\t<option value=\"4\">4日</option>\r\n");
      out.write("\t\t\t\t<option value=\"5\">5日</option>\r\n");
      out.write("\t\t\t\t<option value=\"6\">6日</option>\r\n");
      out.write("\t\t\t\t<option value=\"7\">7日</option>\r\n");
      out.write("\t\t\t\t<option value=\"8\">8日</option>\r\n");
      out.write("\t\t\t\t<option value=\"9\">9日</option>\r\n");
      out.write("\t\t\t\t<option value=\"10\">10日</option>\r\n");
      out.write("\t\t\t\t<option value=\"11\">11日</option>\r\n");
      out.write("\t\t\t\t<option value=\"12\">12日</option>\r\n");
      out.write("\t\t\t\t<option value=\"13\">13日</option>\r\n");
      out.write("\t\t\t\t<option value=\"14\">14日</option>\r\n");
      out.write("\t\t\t\t<option value=\"15\">15日</option>\r\n");
      out.write("\t\t\t\t<option value=\"16\">16日</option>\r\n");
      out.write("\t\t\t\t<option value=\"17\">17日</option>\r\n");
      out.write("\t\t\t\t<option value=\"18\">18日</option>\r\n");
      out.write("\t\t\t\t<option value=\"19\">19日</option>\r\n");
      out.write("\t\t\t\t<option value=\"20\">20日</option>\r\n");
      out.write("\t\t\t\t<option value=\"21\">21日</option>\r\n");
      out.write("\t\t\t\t<option value=\"22\">22日</option>\r\n");
      out.write("\t\t\t\t<option value=\"23\">23日</option>\r\n");
      out.write("\t\t\t\t<option value=\"24\">24日</option>\r\n");
      out.write("\t\t\t\t<option value=\"25\">25日</option>\r\n");
      out.write("\t\t\t\t<option value=\"26\">26日</option>\r\n");
      out.write("\t\t\t\t<option value=\"27\">27日</option>\r\n");
      out.write("\t\t\t\t<option value=\"28\">28日</option>\r\n");
      out.write("\t\t\t\t<option value=\"29\">29日</option>\r\n");
      out.write("\t\t\t\t<option value=\"30\">30日</option>\r\n");
      out.write("\t\t\t\t<option value=\"31\">31日</option>\r\n");
      out.write("\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t</select><br>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"testadd\">主催名</td>\r\n");
      out.write("\t\t\t<td class=\"testadd_main\"><input type=\"text\" name=\"sponsor\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"testadd\">検定名</td>\r\n");
      out.write("\t\t\t<td class=\"testadd_main\"><input type=\"text\" name=\"test_name\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\t<table class=\"button\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td class=\"button\">\r\n");
      out.write("\t\t\t\t<button class=\"button1\" type=\"submit\">確認</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"side\">\r\n");
      out.write("\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/logout\"><button class=\"menu\" type=\"submit\">ログアウト</button></form>\r\n");
      out.write("\t<form action=\"main_admin.html\"><button class=\"menu\" type=\"submit\">メニュートップ</button></form>\r\n");
      out.write("\r\n");
      out.write("\t<p><hr></p>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"test_list.html\" method=\"POST\"><button class=\"menu\" type=\"submit\">検定情報トップ</button></form>\r\n");
      out.write("\t<form action=\"test_add.html\" method=\"POST\"><button class=\"menu\" type=\"submit\">検定の追加</button></form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer>&copy; 2016 WhiteCo.</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
